version: '3'
services:
  jekyll:
      build: .
      environment:
        - JEKYLL_ENV=development
      command: bundle exec jekyll serve --watch --incremental --host 0.0.0.0
      ports:
          - 4000:4000
      volumes:
          - .:/site:cached
          - bundle:/usr/local/bundle:cached

volumes:
  bundle: